version: "2"
services:
  api:
    restart: always
    image: "nginx:1.11.1"
    ports:
      - "443:443"
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - "/etc/letsencrypt/archive/api.geochats.insanecoders.ru:/etc/nginx/ssl:ro"
      - "./api/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./api/conf.d:/etc/nginx/conf.d:ro"
  backend:
    restart: always
    build:
      context: backend
    hostname: backend
    depends_on:
      - storage
    links:
      - storage
    environment:
      DATABASE_ADDR: "mongodb://storage"
      DATABASE_NAME: "geochats"
      LISTEN_ADDR: "0.0.0.0:3000"
  storage:
    restart: always
    image: "mongo:3.3.8"
