version: "2"
services:
  api:
    image: "nginx:1.11.1"
    ports:
      - "443:443"
    network_mode: "host"
    volumes:
      - "/etc/letsencrypt/archive/api.geochats.insanecoders.ru:/etc/nginx/ssl:ro"
      - "./api/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./api/conf.d:/etc/nginx/conf.d:ro"
      - "./api/mocks:/var/lib/geochats/api:ro"
